[package]
name = "gic"
version = "0.2.7"
authors = ["iFaceless <christopherlee199398@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.14"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0"
clap = "2.32.0"
